services:
  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: tikkle
      MARIADB_USER: myuser
      MARIADB_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - tikkle-backend

  mm-db:
    image: mariadb:10.5
    container_name: mm-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: mattermost
      MARIADB_USER: mmuser
      MARIADB_PASSWORD: mmuser_password
    ports:
      - "3307:3306"
    volumes:
      - mm_db_data:/var/lib/mysql
    networks:
      - tikkle-backend

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: mymongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - tikkle-backend

  redis:
    image: redis:6.0
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - tikkle-backend

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - tikkle-backend

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - tikkle-backend

  mattermost:
    image: mattermost/mattermost-team-edition:latest
    restart: unless-stopped
    container_name: mattermost
    ports:
      - "8065:8065"
    environment:
      - MM_SQLSETTINGS_DRIVERNAME=mysql
      - MM_SQLSETTINGS_DATASOURCE=mmuser:mmuser_password@tcp(mm-db:3306)/mattermost?charset=utf8mb4&readTimeout=30s&writeTimeout=30s
      - MM_SERVICESETTINGS_SITEURL=http://localhost:8065
      - MM_SERVICESETTINGS_ENABLEOUTGOINGWEBHOOKS=true
      - MM_SERVICESETTINGS_ENABLEINCOMINGWEBHOOKS=true
      - MM_SERVICESETTINGS_ENABLESIGNUPWITHEMAIL=true
      - MM_SERVICESETTINGS_ENABLEAPIv4=true
      - MM_SERVICESETTINGS_ENABLECUSTOMEMOJI=true
      - MM_SERVICESETTINGS_ENABLEPOSTUSERNAMEOVERRIDE=true
      - MM_SERVICESETTINGS_ENABLEPOSTICONOVERRIDE=true
      - MM_PLUGINSETTINGS_ENABLE=true
      - MM_PLUGINSETTINGS_ENABLEUPLOADS=true
    volumes:
      - mattermost-volume:/mattermost/data
    depends_on:
      - mm-db
    networks:
      - tikkle-backend

networks:
  tikkle-backend:
    name: tikkle-backend
    driver: bridge

volumes:
  mariadb_data:
  mm_db_data:
  mongodb_data:
  mattermost-volume:

