server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/tikkle
    username: myuser
    password: mypassword
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

  data:
    mongodb:
      uri: mongodb://mongoadmin:secret@localhost:27017/mymongodb?authSource=admin
      #      host: localhost
      #      port: 27017
      #      database: mymongodb
      #      username: mongoadmin
      #      password: secret
    redis:
      host: localhost
      port: 6379
      password: '' # 비밀번호 설정 필요 시 추가
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
      enable-auto-commit: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        linger.ms: 1 # 네트워크 과부하 시 해당 값을 올려 배치 처리량을 늘림
logging:
  level:
    root: INFO
    org.apache.kafka: ERROR
    kafka.server.KafkaConfig: ERROR
